#ifndef LIBBLECENTRAL_GLOBAL_H
#define LIBBLECENTRAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBBLECENTRAL_LIBRARY)
#  define LIBBLECENTRALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBBLECENTRALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBBLECENTRAL_GLOBAL_H
